/* ACTION VARIABLE USES FOR REDUCER */

export const SAVE_COMMENTS = 'SAVE_COMMENTS'

export const FETCHING_CHARACTER_REQUEST = 'FETCHING_CHARACTER_REQUEST'
export const FETCHING_CHARACTER_SUCCESS = 'FETCHING_CHARACTER_SUCCESS'
export const FETCHING_CHARACTER_FAILURE = 'FETCHING_CHARACTER_FAILURE'

export const FETCHING_CHARACTER_DETAILS_REQUEST = 'FETCHING_CHARACTER_DETAILS_REQUEST'
export const FETCHING_CHARACTER_DETAILS_SUCCESS = 'FETCHING_CHARACTER_DETAILS_REQUEST'
export const FETCHING_CHARACTER_DETAILS_FAILURE = 'FETCHING_CHARACTER_DETAILS_REQUEST'

/* COMMENTS */
export const ADD_COMMENTS = 'ADD_COMMENTS'
export const LIST_COMMENTS = 'LIST_COMMENTS'
/* URL ENDPOINT API */
export const URL_GLOBAL = 'https://breakingbadapi.com'
export const API_CHARACTER = '/api/characters'
export const API_QUOTES = '/api/quotes'
export const API_RANDOM_QUOTE = '/api/quote/random'